### ISSUE TITLE
Install cleanup

### ISSUE THREAD

**Issue by peterlarkin** [niceandserious/crafty-vagrant#10]
Should we remove `app/src/craft/templates` after installation? Seem a bit redundant after they've been copied across and it could be confusing if you're looking for the craft templates to work on and edit those by mistake!

Would just need to add `rm -R $CRAFT_SRC;` on line 80 of `install.sh`

**Comment by nickautomatic** [comment]
There's definitely something to be said for that - it would reduce the risk of looking at / working on the wrong template.

The only problem there is that could potentially make *developing* Crafty Vagrant (ie. working on the default templates) difficult... (see the [note on development](https://github.com/niceandserious/crafty-vagrant#development) in the README). I guess you could select "no" to that step (ie. don't copy the templates / config) if you want to work on Crafty itself, and point Craft to the default templates instead. That might work.

If it's ok with you I'll test this when I get a chance just to make sure it works ok both ways. If it does then this would definitely be worth doing.

**Comment by peterlarkin** [comment]
Ah yes, didn't think about that. 

Not a huge issue but would be nice to integrate if it doesn't interfere with development on Crafty itself!

**Comment by nickautomatic** [comment]
Ok, this is done. The install process now removes `app/src/craft` unless you add a `--dev` flag when running the install script (ie. `bash install.sh --dev`). That seemed like the neatest solution I could think of.
