### ISSUE TITLE
Require exact version of Browsersync

### ISSUE THREAD

**Issue by nickautomatic** [niceandserious/crafty-vagrant#18]
At the moment we're referencing a numbered version of Browsersync client in the template (2.11.2.js).

If this is the only way of doing this, we should require exactly that version in package.json - otherwise a minor version increase will most likely break live-updating.

Alternatively (ideally), maybe there's a way of referencing the Browsersync client that doesn't require specifying a particular version number.

**Comment by nickautomatic** [comment]
For the record, I've now pushed out a new package.json that specifies an exact version of Browsersync. It would be nice to find a way of not having to hard-code the version number in the snippet in _layout.twig, but I can't find a documented way of doing that right now...

**Comment by peterlarkin** [comment]
Just found that there is a way to fix this by removing the version number all together resolves to the correct file. See https://github.com/BrowserSync/browser-sync/issues/82
