### ISSUE TITLE
403 Forbidden on after renaming public/ folder

### ISSUE THREAD

**Issue by chrishiam** [niceandserious/crafty-vagrant#23]
I'm using Beanstalk to deploy to a live server, but I need to match my development environment to my production (i.e. I had to change the `public/` folder to `public_html/`).

The problem is after changing the directory name I'm now getting hit with `403 Forbidden` when visiting `craft.dev` — I'm sure there's just a line in a file somewhere I need to change but I can't find it.

Any suggestions?

**Comment by nickautomatic** [comment]
The Apache VirtualHost is set up to use `app/public` as the document root, so if you just rename the folder, Apache won't know where to find the public directory any more. You'll need to update Apache's config to point to the new location.

Crafty Vagrant's Apache configuration is at `puppet/manifests/vagrant_webroot.conf`. You'll probably need to update the location of the public directory there: ie. replace the two instances of `public` with `public_html`. Having made that change, a `vagrant provision` should re-provision your Vagrant environment with the updated settings. I don't _think_ that should do anything to the database, but it would be sensible to make sure you've got a backup before you do that.

If that doesn't fix it, someone else was having deployment problems related to renaming the public folder last week. They got it working in the end, so [that thread](https://github.com/niceandserious/crafty-vagrant/issues/19#issuecomment-210132176) might also be worth looking at.

**Comment by chrishiam** [comment]
Editing the `vagrant_webroot.conf` file and running `vagrant provision` fixed the problem. Thanks for the fast reply, hopefully this will be helpful to others too.

**Comment by nickautomatic** [comment]
Excellent. No problem - glad that fixed it!
