### ISSUE TITLE
Replacing database with newer one

### ISSUE THREAD

**Issue by chrishiam** [niceandserious/crafty-vagrant#24]
We have a production server with a database which has now deprecated our development/local one. What I want to do is export the `.sql` file from the latest database and replace our old, outdated one. Is there a way to do this without disrupting everything or starting from scratch?

One thing that bugs me with Craft is trying to keep both databases in sync. I've tried remote connecting to the production database from the local setup, but it causes more problems (can't use BrowserSync, keep getting logged out, etc).

**Comment by nickautomatic** [comment]
Hi. Crafty has a database provisioning script that will do exactly this. See the instructions in the [README](https://github.com/niceandserious/crafty-vagrant#usage). Let us know if you have any problems.
