### ISSUE TITLE
PHP 7?

### ISSUE THREAD

**Issue by toddprouty** [niceandserious/crafty-vagrant#28]
Any plans to include PHP 7 or create a fork that does? I hear there are [significant improvements in speed](https://pixelandtonic.com/blog/php-7)  for Craft.

**Comment by peterlarkin** [comment]
@toddprouty You're in luck! @nickautomatic has been working on a [PHP 7 feature branch](https://github.com/niceandserious/crafty-vagrant/tree/feature/php7.0). We haven't had a chance to fully test it out yet, but if you want to give it a try, let us know you get on. We're hoping to merge it into `master` soon.

**Comment by hisnameisjimmy** [comment]
How is progress going on the PHP7 branch? I'm also curious about this for performance reasons.

**Comment by nickautomatic** [comment]
@hisnameisjimmy The Vagrant box that we're currently using on the PHP 7 feature branch seems to have issues on some versions of OSX. We're currently trying a different Vagrant box to see if that's more reliable, but we won't merge into master until it's working smoothly on all our machines.

In the mean time, [the feature branch](https://github.com/niceandserious/crafty-vagrant/tree/feature/php7.0) might be worth trying. If you do, we'd be interested to know if it works for you.

**Comment by peterlarkin** [comment]
We've been using the php7 branch for a little while now and all seems to be good with the latest versions of VirtualBox and Vagrant as far I can tell. 

We should consider merging this unless anyone else has experienced any issues?

Although we might need to fix/revert [this commit](https://github.com/niceandserious/crafty-vagrant/commit/1f45554deb8c5e85a23542f571319dc395e920cd) on master as I think it broke some things if I recall correctly? cc @marcellegane

**Comment by peterlarkin** [comment]
Whoops. Just seen there's already a PR open and ready to go (#33). Will wait for @marcellegane to confirm.
