### ISSUE TITLE
Default login for Ubuntu in dev.mode?

### ISSUE THREAD

**Issue by chrisdubya** [niceandserious/crafty-vagrant#32]
Hey,

In development mode what are the default login in details for Ubuntu?

When I login to the Virtual Box console, I'm prompted with the following: 

    Ubuntu 14.04.05 LTS craft tty1
    craft login: _

Poked around the puppet manifests and Vagrantfile and couldn't find anything.  Only clue I could get was when you boot the VM you get 

    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...

**Comment by nickautomatic** [comment]
Hey @chrisdubya. Hope you're well!

Instead of trying to log in via VirtualBox, have you tried `vagrant ssh`? I don't think you should need a login that way.

**Comment by chrisdubya** [comment]
Ahhh, brilliant! Thanks @nickautomatic!

**Comment by nickautomatic** [comment]
No probs @chrisdubya! Glad it worked for you!
