### ISSUE TITLE
Multi environment config

### ISSUE THREAD

**Issue by peterlarkin** [niceandserious/crafty-vagrant#9]
As part of the install process, it'd be nice if we were to overwrite the `general.php` and `db.php` files with some basic setup for multi environment configurations. This way, rather than rewriting them each time, we can just plug in the right credentials for the staging and production servers. 

There's an interesting example [here](https://github.com/BarrelStrength/Craft-Multi-Environment-Config). @nickautomatic, what do you reckon?

**Comment by nickautomatic** [comment]
Yes, definitely a good idea! In fact, Crafty actually already does that! (...albeit with a *very* basic setup). As part of the install process, the install.sh script optionally copies the contents of `src/craft` into Craft's directory, overwriting default files with the same path.

At the moment there's not much to Crafty's [`general.php`](https://github.com/niceandserious/crafty-vagrant/blob/master/app/src/craft/config/general.php) and [`db.php`](https://github.com/niceandserious/crafty-vagrant/blob/master/app/src/craft/config/db.php) though, so definitely worth thinking about anything that would be good to always have in there.

I really like the way they set siteUrl in that example - would be great to have siteUrl configured and working out of the box for any environment - so I'll add that right now.

**Comment by nickautomatic** [comment]
Ok, both `general.php` and `db.php` now provide a basic setup for multiple environments, including defining the {siteUrl} environment variable automatically.
